### ISSUE TITLE
Numbers starting with zero gets error

### ISSUE THREAD

**Issue by mailto-kkk** [tdegrunt/jsonschema#163]
I tried to validate JSON data with the below schema. 

ValidateData.PAYMENT_TYPE_JSON_SCHEMA = {
    "id": "/PaymentType",
    type: 'object',
    properties: {
        "purchaseAmount": {
            required: true,
            type: "number",
            pattern:"^[1-9]+[0-9]*$"
        } 
    },
    "additionalProperties": false
};

It is working fine. It is accepting only positive numbers, without any decimal points
But if I give any numbers starting with zero(For ex, 012), I am getting below error.

SyntaxError: Unexpected number
    at Object.parse (native)
    at parse (C:\node_modules\kraken-js\node_modules\body-parser\lib\types\json.js:88:17)
    at C:\\node_modules\kraken-js\node_modules\body-parser\lib\read.js:116:18

**Comment by mailto-kkk** [comment]
@Acubed

**Comment by tdegrunt** [comment]
Error seems in a different library? Kraken-Js?

**Comment by mailto-kkk** [comment]
yes, that's what I am getting confusion. Before reaching the validation schema validation, kraken-js is throwing me out.

I also noted one more point, if the type of the property is declared as 'String'(instead of number), it is working fine.

**Comment by tdegrunt** [comment]
Just try this out in jsonschema, like the examples, it works there. The problem is likely with kraken-js.

**Comment by tdegrunt** [comment]
Closing due to inactivity
