### ISSUE TITLE
Throws when parsing the meta-schema of JSON Schema

### ISSUE THREAD

**Issue by arty-name** [tdegrunt/jsonschema#172]
I was trying to make sure that my schema is right by validating it against the [official meta-schema](http://json-schema.org/schema). I got following exception:

```
SchemaError: no such schema <http://json-schema.org/draft-04/schema#/definitions/positiveInteger>
    at Validator.resolve (node_modules/jsonschema/lib/validator.js:258:11)
    at Validator.validateSchema (node_modules/jsonschema/lib/validator.js:209:25)
    at Validator.validateProperties (node_modules/jsonschema/lib/attribute.js:173:20)
    at Validator.validateSchema (node_modules/jsonschema/lib/validator.js:221:34)
    at Validator.validate (node_modules/jsonschema/lib/validator.js:150:23)
    at module.exports.validate (node_modules/jsonschema/lib/index.js:11:12)
    at Request._callback (repl:1:78)
    at Request.self.callback (node_modules/request/request.js:200:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
```

Here is the code to reproduce: 

``` javascript
    var validate = require('jsonschema').validate;
    var request = require('request');
    var r = request('http://json-schema.org/schema', function(e, res, body){ 
        console.log(validate({}, JSON.parse(body)).errors)
    });
```

Interestingly enough, things start working if I delete `"id": "http://json-schema.org/draft-04/schema#",` from the meta-schema.

**Comment by Acubed** [comment]
We don't actually need 'request' here, removing that suffices to reproduce the problem:

```javascript
var validate = require('jsonschema').validate;
var metaschema = require('jsonschema/schema/draft-04/schema.json');
console.log(validate({}, metaschema).errors);
```

When using `$ref`, it's a better bet to use `Validator`:

```javascript
var Validator = require('jsonschema').Validator;
var metaschema = require('jsonschema/schema/draft-04/schema.json');
var v = new Validator;
v.addSchema(metaschema);
console.log(v.validate({}, metaschema).errors)
```

I can't think of any obvious reason your code should fail, though.

**Comment by jasonkarns** [comment]
Minimal test case:

```
require('jsonschema').validate({}, require('jsonschema/schema/draft-04/schema.json'));
```

**Comment by awwright** [comment]
I can't seem to reproduce this anymore, using the `json-metaschema` package like so:

```javascript
require('chai').should();

var Validator = require('..').Validator;
var metaschema = require('json-metaschema/draft-04-schema.json');

describe('Meta-schema', function () {

  beforeEach(function () {
    this.validator = new Validator();
  });

  it('validates itself', function () {
    this.validator.validate(metaschema, metaschema).valid.should.be.true;
  });

});
```

If this is still causing any trouble, please open a new issue with a minimal test case.
