### ISSUE TITLE
JSON Pointer($ref) doesn't work with # symbol

### ISSUE THREAD

**Issue by freeart** [tdegrunt/jsonschema#204]
[https://spacetelescope.github.io/understanding-json-schema/structuring.html](https://spacetelescope.github.io/understanding-json-schema/structuring.html)

```
const Validator = require('jsonschema').Validator;

let ref = {
    "type": "object",
    "properties": {
        "lat": {
            "type": "number",
            "required": true
        },
        "long": {
            "type": "number",
            "required": true
        }
    }
}
let schema = {
    "type": "object",
    "properties": {
        "body": {
            "$ref": "#/definitions/Test"
        }
    }
};

let data = {
    "body": {"lat": 0, "long": 0}
};

let v = new Validator();
v.addSchema(ref, '#/definitions/Test');
let validation = v.validate(data, schema);

/*
SchemaError: no such schema #/definitions/Test located in </>
    at Validator.resolve (/home/pavel/mapit20-server/node_modules/jsonschema/lib/validator.js:276:11)
    at Validator.validateSchema (/home/pavel/mapit20-server/node_modules/jsonschema/lib/validator.js:199:25)
    at Validator.validateProperties (/home/pavel/mapit20-server/node_modules/jsonschema/lib/attribute.js:191:20)
    at Validator.validateSchema (/home/pavel/mapit20-server/node_modules/jsonschema/lib/validator.js:211:34)
    at Validator.validate (/home/pavel/mapit20-server/node_modules/jsonschema/lib/validator.js:150:23)
    at Object.<anonymous> (/home/pavel/mapit20-server/test.js:36:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
*/
```

**Comment by awwright** [comment]
@freeart Validator#addSchema needs to be provided an absolute URI (non-relative without a fragment... I suppose you can still include a fragment, but the behavior is undefined). Try that and let me know what the result is.

I suppose there should be an error message to this effect.

**Comment by freeart** [comment]
@awwright without # works fine, addSchema accept '/definitions/Test' Also I tried to add big leaf "/definitions/A", "/definitions/B". etc. with ~10 elements and it works.

**Comment by awwright** [comment]
@freeart If it's working in some cases without an absolute URI, then you've just run into a fluke. addSchema expects an absolute URI, such as `http://example.com/schema/Test.json`.

The relative URI provided in the $ref only makes sense if there's a base URI established somewhere else, for example:

```javascript
{
   "id": "http://example.com/schema/",
    "type": "object",
    "properties": {
        "body": {"$ref": "Test.json"}
    }
 }
```

This would be the same as saying `{"$ref": "http://example.com/schema/Test.json"}`.
