### ISSUE TITLE
Fails to load JSON Schema draft-7 meta-schema

### ISSUE THREAD

**Issue by lennygran** [tdegrunt/jsonschema#250]
Fails to load JSON Schema draft-7 meta-schema at http://json-schema.org/draft-07/schema

The error is:
```
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at urlParse (url.js:75:5)
    at Object.urlResolve [as resolve] (url.js:642:10)
```

The code:
```
    var metaschema7 = require("./JSON-meta-schema-draft7.json");
    var Validator = require('jsonschema').Validator;
    var validator7 = new Validator();

    function importNextSchema(validator, metaschema) {
        var nextSchema = validator.unresolvedRefs.shift();
        if (nextSchema) {
            var nextName = nextSchema.split('/');
            validator.addSchema(metaschema.definitions[nextName[nextName.length - 1]], nextSchema);
            importNextSchema(validator, metaschema);
        };
    };
    importNextSchema(validator7, metaschema7);
```
Debugging note: looks like tool does not recognize `$id` defined by *draft-7*.

**Comment by awwright** [comment]
Yeah it's probably related to "$id" support, I'll fix that pretty soon here.

**Comment by awwright** [comment]
This code sample works for me as of e2f78b7332e7da0f732efd95c5563462a962b74e and will be available in the next release (minor release).
