### ISSUE TITLE
Crash when type is number but validation is expecting integer

### ISSUE THREAD

**Issue by enozero** [tdegrunt/jsonschema#259]
jsonschema version `1.2.4`
Node version `9.3.0`

Sample JSON:
```json
{
  "foo": 1.1
}
```

Swagger Schema:
```yml
Data:
  id: "/Foo"
  properties:
    foo:
      type: integer
```

Code:
```js
const { Validator } = require('jsonschema');
const validator = new Validator();
validator.validate(json, schema);
```

Error:
```
TypeError: Cannot read property 'id' of null
    at /Users/me/src/harness/node_modules/jsonschema/lib/attribute.js:50:16
    at Array.map (<anonymous>)
    at Validator.validateType (/Users/me/src/harness/node_modules/jsonschema/lib/attribute.js:49:22)
    at Validator.validateProperties (/Users/me/src/harness/node_modules/jsonschema/lib/attribute.js:199:20)
    at Validator.validateSchema (/Users/me/src/harness/node_modules/jsonschema/lib/validator.js:197:34)
    at Validator.validate (/Users/me/src/harness/node_modules/jsonschema/lib/validator.js:124:23)
```

My expectation is that it shouldn't crash. Rather, it should return the `ValidatorResult` and the `errors` array should contain an error.

**Comment by enozero** [comment]
This was completely our bad... `jsonschema` is doing the right thing. We had `null` as a type instead of `"null"`. That was the root issue.
