### ISSUE TITLE
Circular Dependency Warnings in latest Node v14.15.1

### ISSUE THREAD

**Issue by spydercavern** [tdegrunt/jsonschema#326]
Hi,
I have recently updated the node version to v14.15.1, but with this upgrade, i see a lot of warnings like below from json schema project. I currently use the 1.4.0 version of jsonschema in the project.
Node Version  v14.15.1
jsonschema 1.4.0

Warning logs- 
(node:55774) Warning: Accessing non-existent property 'not' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at scanSchema (/node_modules/jsonschema/lib/scan.js:56:39)
    at scanArray (/node_modules/jsonschema/lib/scan.js:61:7)
    at scanSchema (/node_modules/jsonschema/lib/scan.js:54:5)
    at scanObject (/node_modules/jsonschema/lib/scan.js:67:7)
    at scanSchema (/node_modules/jsonschema/lib/scan.js:47:5)
[jsonschema-warnigns.log](https://github.com/tdegrunt/jsonschema/files/5558149/jsonschema-warnigns.log)

    at scanArray (/node_modules/jsonschema/lib/scan.js:61:7)
    at scanSchema (/node_modules/jsonschema/lib/scan.js:44:5)
    at scanArray (/node_modules/jsonschema/lib/scan.js:61:7)
Also Attached the partial logs

**Comment by awwright** [comment]
I'm not seeing any errors like this. Can you provide an example of what you're doing to see this? Is it possible to write a test?

**Comment by awwright** [comment]
@spydercavern I cannot reproduce this. Would you be able write a minimal test that will produce this error?

**Comment by awwright** [comment]
I can't reproduce this and I can't tell what might be causing this, please file a new issue with some code that reproduces the issue.
