### ISSUE TITLE
invalid schema with a property set to "undefined" causes TypeError exception during validation

### ISSUE THREAD

**Issue by jkryl** [tdegrunt/jsonschema#60]
I got following exception when using jsonschema:

```
Uncaught exception: TypeError: Cannot read property 'id' of undefined, stack:
    at SchemaContext.makeChild (/root/nef/node_modules/jsonschema/lib/helpers.js:100:43)
    at Validator.validateProperties (/root/nef/node_modules/jsonschema/lib/attribute.js:153:76)
    at Validator.validateSchema (/root/nef/node_modules/jsonschema/lib/validator.js:208:34)
    at Validator.validate (/root/nef/node_modules/jsonschema/lib/validator.js:137:23)
    at Object.module.exports.validate (/root/nef/node_modules/jsonschema/lib/index.js:11:12)
    at Object.validate (/root/nef/lib/nef/schemaUtils.js:223:29)
    at /root/nef/node_modules/async/lib/async.js:229:13
```

It took me a day until I figured out that the error is caused by invalid JSON schema where definition of one of the properties is set to undefined. I.e.

```
{
   "type": "object",
   "properties": {
        "a": { "type": string },
        "b": undefined
   }
}
```

for loop iterating over schema properties in attribute.js:validators.properties() will yield attribute "b" (although it is set to undefined) and undefined value is then passed to ctx.makeChild() where exception is thrown when trying to reference 'id' attribute of undefined.

Two things which need to fixed here:
- when such schema is validated by JSON schema (http://json-schema.org/draft-03/schema) it should report error, currently it passes the validation.
- when the schema is used for validation it should either skip undefined property during validation or throw SchemaError.

**Comment by awwright** [comment]
This should be fixed in 326e43eeaee5b667ad06fcf368350ae9cef9fb1c:

* Undefined values in "properties" and "patternProperties" should be handled the same as no value
* Null values will throw a better error
